"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import dotenv
dotenv.load_dotenv()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load SECRET_KEY from environment (dotenv is already loaded above).
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Read DEBUG from environment and convert to boolean.
def _str_to_bool(value: str | None) -> bool:
    if value is None:
        return False
    return str(value).lower() in ("1", "true", "yes", "on")

DEBUG = _str_to_bool(os.environ.get('DEBUG'))
# Validate SECRET_KEY presence. Fail fast in non-development (DEBUG=False).
if not SECRET_KEY:
    if DEBUG:
        # In development allow an explicit insecure default but warn loudly.
        import warnings

        warnings.warn(
            "SECRET_KEY environment variable is not set. Using an insecure default SECRET_KEY for development. "
            "Set SECRET_KEY in your .env or environment for production."
        )
        SECRET_KEY = 'insecure-development-key-change-me'
    else:
        raise RuntimeError(
            "Missing required environment variable: SECRET_KEY.\n"
            "Set SECRET_KEY in the environment (for example in a .env file).\n"
            "Example: SECRET_KEY='django-insecure-<your-random-key>'"
        )

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clientes.apps.ClientesConfig',
    'contratos.apps.ContratosConfig',
    'financeiro.apps.FinanceiroConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration - explicitly validate env vars to provide clear errors
_required_db_keys = [
    "DB_ENGINE",
    "DB_HOST",
    "DB_PORT",
    "DB_NAME",
    "DB_USER",
    "DB_PASSWORD",
]

_missing_db = [k for k in _required_db_keys if not os.environ.get(k)]

if _missing_db:
    if DEBUG:
        # Fall back to a local sqlite database in development to make running tests/dev easy.
        import warnings

        warnings.warn(
            "Missing DB environment variables: %s. Falling back to sqlite for development.\n"
            "To use Postgres/other DBs set these variables in your environment or .env.\n"
            "Example values:\n"
            "  DB_ENGINE=django.db.backends.postgresql\n"
            "  DB_HOST=localhost\n"
            "  DB_PORT=5432\n"
            "  DB_NAME=financeiro\n"
            "  DB_USER=postgres\n"
            "  DB_PASSWORD=supersecret\n"
            % (", ".join(_missing_db),)
        )

        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
    else:
        raise RuntimeError(
            "Missing required DB environment variables: %s.\n"
            "Set the following environment variables before starting the app (examples shown):\n"
            "  DB_ENGINE=django.db.backends.postgresql\n"
            "  DB_HOST=localhost\n"
            "  DB_PORT=5432\n"
            "  DB_NAME=financeiro\n"
            "  DB_USER=postgres\n"
            "  DB_PASSWORD=supersecret\n"
            % (", ".join(_missing_db),)
        )
else:
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('DB_ENGINE'),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': os.environ.get('DB_PORT'),
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
        }
    }


"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}"""


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
