# Generated by Django 5.2.8 on 2025-11-20 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, help_text='Código do banco (BACEN) ou identificador interno.', max_length=10, null=True)),
                ('identificador_layout_extrato', models.CharField(blank=True, help_text='Identificador do layout de extrato (PDF/OFX) deste banco.', max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Centro de custo',
                'verbose_name_plural': 'Centros de custo',
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Apelido da conta: Nubank PJ, Inter PF, Itaú Poupança, etc.', max_length=100)),
                ('tipo_conta', models.CharField(choices=[('CORRENTE', 'Corrente'), ('POUPANCA', 'Poupança'), ('OUTRA', 'Outra')], default='CORRENTE', max_length=10)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('numero', models.CharField(blank=True, help_text='Número/identificação da conta (opcional).', max_length=50, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Saldo de abertura de controle no sistema.', max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='financeiro.banco')),
            ],
            options={
                'verbose_name': 'Conta bancária',
                'verbose_name_plural': 'Contas bancárias',
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField(help_text='Data de competência ou da movimentação.')),
                ('data_vencimento', models.DateField(blank=True, help_text='Usado para controle de vencimento (ex: boletos a pagar/receber).', null=True)),
                ('situacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('nota_fiscal_emitida', models.BooleanField(default=False, help_text='Marque quando a NF referente a este lançamento for emitida.')),
                ('eh_extra', models.BooleanField(default=False, help_text='Marque se este lançamento é um serviço extra/pontual fora do combinado base.')),
                ('aviso_vencimento_enviado', models.BooleanField(default=False, help_text='Marcado quando já foi enviado aviso de vencimento.')),
                ('aviso_nf_enviado', models.BooleanField(default=False, help_text='Marcado quando já foi enviado aviso de emissão de NF pendente.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.categoria')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.centrocusto')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='clientes.cliente')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.contabancaria')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='contratos.contrato')),
                ('item_contrato', models.ForeignKey(blank=True, help_text='Se este lançamento for decorrente de um contrato, vincule o item aqui.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='contratos.itemcontrato')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
