# Generated by Django 5.2.8 on 2025-11-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_documento_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(help_text='CPF ou CNPJ (apenas números ou formatado).', max_length=20, unique=True),
        ),
    ]
