# Generated by Django 5.2.8 on 2025-12-23 15:43

import contratos.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratodocumento',
            name='arquivo',
            field=models.FileField(help_text='Envie o PDF assinado ou outro documento relacionado ao contrato.', upload_to=contratos.models.contrato_documento_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
